name: "Run unit tests"

on:
  - push

jobs:
  test:
    name: Run tests (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          extensions: exif,json,mbstring

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Add GitHub Actions printer for PHPUnit
        run: composer require --dev --no-update mheap/phpunit-github-actions-printer

      - name: Login for Laravel Nova
        run: composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_TOKEN}
        env:
          NOVA_USERNAME: ${{ secrets.NovaUsername }}
          NOVA_TOKEN: ${{ secrets.NovaApiToken }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1
        with:
          composer-options: "--ignore-platform-req=php"
          dependency-versions: highest # No lockfile is present, so locked (the default) isn't possible

      - name: Run unit tests
        run: vendor/bin/phpunit --printer mheap\\GithubActionsReporter\\Printer
